repos:
  - repo: local
    hooks:
      - id: block-root-test-files
        name: Block root test files
        entry: scripts/check_root_test_files.sh
        language: system
        pass_filenames: true
        files: \.py$
      - id: block-root-python-files
        name: Block root python files
        entry: scripts/check_root_python_files.sh
        language: system
        pass_filenames: true
        files: \.py$
